@startuml
'https://plantuml.com/class-diagram

class Employee {
    -String firstName
    -String lastName
    -int salary

    +String getFirstName()
    +String getLastName()
    +int getSalary()
}

class Solution {
    -List<Employee> readEmployeeListFromFile()
    -void displayEmployeeList()
    -String getFormattedStringFromList()
}

@enduml