@startuml
'https://plantuml.com/class-diagram

class Solution {
    -String getProductNameFromUser()
    -String getInventoryFileAsString(String path)
    +Inventory getInventoryFromJSON(String path)
}

class Inventory {
    -Product[] products
    -HashMap<String, Product> productsMap
    -void createSearchMap()

    +boolean isProductInInventory(String name)
    +Product getProductFromSearch(String name)
}

class Product {
    -String name
    -double price
    -int quantity

    +String getName() // used for creating hashmap later
    +String toString() // override using our format
}

Inventory *-- Product : contains many

@enduml