@startuml
'https://plantuml.com/class-diagram

class Solution {
    ' constants
    -String INPUT_PATH = "data/exercise45_input.txt"
    -String REPLACE_ME = "utilize"
    -String REPLACEMENT = "use"

    +String readFileToString(String inputPath)
    -String getOutputFileNameFromUser()
    +String replaceWordInString(String content, String replaceMe, String replacement)
    +void writeStringToFile(String outputPath, String fileName, String content)
}

@enduml